AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFlaskFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: gptj_server.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Timeout: 900
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          APP_ENV: 'production'
    Events:
      Api:
        Type: Api
        Properties:
          Path: /{proxy+}
          Method: ANY
